### ISSUE TITLE
Using RWO PVCs leads to problems

### ISSUE THREAD

**Issue by stblassitude** [bootc/netbox-chart#87] opened 2022-04-03 07:29 UTC
There appears to be an implicit assumption that the media volume is ReadWriteMany (RWX). When it is an RWO PVC, the housekeeping job can never run, and restarting the netbox pod will also hang since the init container implicitly wants to mount media as well; since it is already mounted by the running pod, the new pod is stuck in PodInitializing.

```
  Warning  FailedMount  59s (x2 over 12m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[media], unattached volumes=[secrets netbox-tmp media optunit kube-api-access-5xsr8 config]: timed out waiting for the condition

**Comment by stblassitude** [comment] 2022-04-03 08:23
A possible workaround for at least some storage classes: force all pods to be on the same node (works for local-path and Longhorn).

Example tying all pods to a specific node:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - "kehhq-k3s"

housekeeping:
  podSecurityContext:
    fsGroup: 1000
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - "kehhq-k3s"

worker:
  podSecurityContext:
    fsGroup: 1000
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - "kehhq-k3s"

**Comment by stblassitude** [comment] 2022-04-03 10:08
Setting the housekeeping nodeselector requires the change from #88 .

**Comment by bootc** [comment] 2022-04-26 19:51
This is a duplicate of #70 but I do really appreaciate the PR! I'll link it there.

**Closed by bootc** 2022-04-26 19:51 UTC
