### ISSUE TITLE
Unable to configure Netbox

### ISSUE THREAD

**Issue by eversC** [bootc/netbox-chart#12] opened 2020-03-09 21:49 UTC
This may be an issue upstream but thought I'd check in here quickly first... I don't seem to be able to make any changes to the Netbox configuration.

The values.yaml I'm using only has changes to postgres + redis compared to the one in the root of this project.

I'm specifically interested in Netbox's `LOGIN_REQUIRED` and `METRICS_ENABLED` config settings.

`LOGIN_REQUIRED` doesn't appear to work, as I can't access anything anonymously (which is what I'm after). This is weird in itself as it should default to `False`.

`METRICS_ENABLED` also doesn't work; I get a Page Not Found error when I hit the `/metrics` page.

I've followed the `netbox-chart` config all the way through from k8s configmaps to inspecting `/run/config/netbox/netbox.yaml` on the pod, and they seem fine, so currently I'm suspecting `netbox-docker`.

**Comment by bootc** [comment] 2020-03-09 22:34
Would you mind supplying a test case in the form of a `values.yaml` file or similar so that I can try to reproduce what you're seeing, please?

**Comment by eversC** [comment] 2020-03-12 22:44
Hey @bootc 

sorry for delay. GH doesn't support yaml file attachments, so just added the txt suffix, here goes...

[values.yaml.txt](https://github.com/bootc/netbox-chart/files/4326938/values.yaml.txt)

**Comment by eversC** [comment] 2020-04-06 15:06
Hi @bootc 👋 

Did you manage to reproduce the problem?

**Comment by bootc** [comment] 2020-04-26 15:58
Hi @eversC - sorry I haven't had a chance to look at this until now. I'm investigating now and making sure my chart isn't doing anything funky. Did you get anywhere with this, out of interest?

**Comment by bootc** [comment] 2020-04-26 16:25
I can definitely replicate the `LOGIN_REQUIRED` / `loginRequired` behaviour, although it looks like the chart is doing the right things to make it work. I'll keep looking into that. The metrics, however, do seem to show up when enabled with `metricsEnabled` set to true.

**Comment by bootc** [comment] 2020-04-26 16:51
So the `loginRequired` setting _is_ working, but perhaps doesn't behave in an obvious manner. When set to `true` I can't even get to the home page without a login. When it's `false` I can see the home page but I can't access any views. Additionally setting `exemptViewPermissions: ['*']` permits all views to be accessed without logging-in as expected.

So I think this is all working as designed, but the upstream NetBox documentation isn't very clear about how this works anymore; the only documentation I can really find about this is at:

https://netbox.readthedocs.io/en/stable/release-notes/version-2.6/#view-permissions-323

Given this is an upstream problem I'll close this now.

**Closed by bootc** 2020-04-26 16:51 UTC
Labels: bug, more info

**Comment by eversC** [comment] 2020-04-26 20:21
Ah thanks for spending some time on this. Now that I'm aware of the `exemptViewPermissions` config setting it seems to be everywhere in the Netbox doco! I guess, as you said, it's not very clear and I didn't make the link between that and the `loginRequired` setting. I may raise an issue in the Netbox repo at some point. 

All working for me now.

Turns out the `metricsEnabled` 'issue' was just pure PEBCAK.

Thanks again!
