### ISSUE TITLE
Postgres restart leads to permission error

### ISSUE THREAD

**Issue by tobikris** [bootc/netbox-chart#11] opened 2020-03-04 10:09 UTC
There is an issue (https://github.com/helm/charts/issues/13651) that was solved. This chart should use the dependency version 8.5.x to work around this.

```
postgresql 10:02:45.28
postgresql 10:02:45.28 Welcome to the Bitnami postgresql container
postgresql 10:02:45.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 10:02:45.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 10:02:45.29 Send us your feedback at containers@bitnami.com
postgresql 10:02:45.29
postgresql 10:02:45.33 INFO ==> ** Starting PostgreSQL setup **
postgresql 10:02:45.45 INFO ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:02:45.46 INFO ==> Loading custom pre-init scripts...
postgresql 10:02:45.47 INFO ==> Initializing PostgreSQL database...
postgresql 10:02:45.49 INFO ==> postgresql.conf file not detected. Generating it...
postgresql 10:02:45.52 INFO ==> pg_hba.conf file not detected. Generating it...
postgresql 10:02:45.52 INFO ==> Generating local authentication configuration
postgresql 10:02:45.55 INFO ==> Deploying PostgreSQL with persisted data...
postgresql 10:02:45.56 INFO ==> Configuring replication parameters
postgresql 10:02:45.61 INFO ==> Configuring fsync
postgresql 10:02:45.63 INFO ==> Loading custom scripts...
postgresql 10:02:45.64 INFO ==> Enabling remote connections
postgresql 10:02:45.66 INFO ==> Stopping PostgreSQL...
postgresql 10:02:45.67 INFO ==> ** PostgreSQL setup finished! **

postgresql 10:02:45.77 INFO ==> ** Starting PostgreSQL **
2020-03-04 10:02:45.804 GMT [1] FATAL: data directory "/bitnami/postgresql/data" has invalid permissions
2020-03-04 10:02:45.804 GMT [1] DETAIL: Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

**Comment by bootc** [comment] 2020-03-05 08:12
Which version of the chart are you using? The requirements specify 8.x.x since at least chart 1.0.2 so you should be fine if you upgrade.

**Comment by timmy59100** [comment] 2020-03-18 14:55
I've got the same issue with chart version 8.6.3.
With the last version I used 8.1.5 it is working correctly.

**Comment by bootc** [comment] 2020-04-26 16:06
Closing because I can't reproduce this and the chart doesn't bundle the buggy version (anymore at least!).

**Closed by bootc** 2020-04-26 16:06 UTC
Labels: bug, more info
